# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :osx, '10.10'

target 'DMMacPickImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DMMacPickImage
  pod 'SDWebImage', '~> 4.3.3'

end
